package com.anilscript.GetAPIwz.model;
import jakarta.persistence.*;
import lombok.*;
import org.locationtech.jts.geom.Geometry;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;

@Data
@NoArgsConstructor
@AllArgsConstructor
public class SupportStructureModel {

    private Integer ogc_fid;
//    private String comments;
//    private String jobid;
//    private LocalDate installationdate;
    private Long subtypecd;
    private String subStationCode;
//    private String owner;
//    private BigDecimal symbolrotation;
    private String poleCode;
//    private String status;
//    private String material;
//    private String height;
//    private String foundationtype;
//    private String grounded;
//    private Long polecount;
//    private String style;
//    private String treatmenttype;
//    private String manufacturer;
//    private LocalDate datemanufactured;
//    private String serialnumber;
//    private String conductorsupport;
//    private BigDecimal mountingheight;
//    private Long ratedampere;
    private String feederCode;
//    private String typeofsupport;
//    private String sizeofcrossarm;
//    private String noofinsulators;
//    private String insulatormaterial;
//    private String studpoles;
//    private String rmsnumber;
//    private String gurading;
//    private String noofvibrationdampers;
//    private String muffing;
    private String estimateno;
//    private LocalDate estimatesanctiondate;
//    private String ponumber;
//    private LocalDate purchasedate;
//    private LocalDate commissioningdate;
    private String feederType;
//    private String poleusability;
//    private String crossarmtype;
//    private String archingrods;
//    private String compositeline;
//    private String supportstr;
//    private String diameter;
//    private Integer enabled;
//    private String tempSurveyCode;
//    private String dimension;
//    private String crossarmsizeLt;
//    private String mainprotectionLt;
//    private String servicelineprotectionLt;
//    private String wirematerial;
//    private String wiresize;
//    private String anchortype;
//    private String rodtype;
//    private Integer noofsupppolesGoodcondition;
//    private Integer noofsupppolesBadcondition;
//    private Integer noofsuppwiresGoodcondition;
//    private Integer noofsuppwiresBadcondition;
//    private String anchorguyRemarks;
//    private String workorderid;
//    private String reltransformerid;
//    private String crossarmtypeLt;
//    private String paintcode;
//    private String projectno;
//    private String taskno;
//    private String assetlineid;
    private Geometry wkbGeometry;

//    private String townId;
    private String subdivisionId;
    private String divisionId;
    private String circleId;
//    private String dtrCode;
    private String createdBy;
    private LocalDate createdDatetime;
    private String modifiedBy;
    private LocalDate modifiedDatetime;
    private String feederName;
//    private Integer insulatorType;
    private String surveyType;
    private Integer poleTypeSubtypecd;
    private Integer supportStructureType;
    private Integer poleAbSwitch;
    private Integer conductorType;
    private Integer conductorSize;
    private String parentPoleCode;
    private String objectid;
    private Integer poleNumber;
    private Integer numberOfCircuit;
//    private String subdivisionIds;
//    private Integer noofcircui;
    private String circleName;
    private String divisionName;
    private String subdivisionName;
//    private String townName;
//    private Boolean isInsideSubstation;
    private String ssName;
//    private String ssCode;
//    private Geometry wkbGeometryBck;
//
//    private String geom;
//    private String feederTypeBak;
//    private String feederCodeBck;
//    private String feederNameBck;
    private Integer poleSequence;
//    private String dtrUniqueCode;
//    private Integer supportStructureTypeOld;
//    private String facilityid;
    private String dataType;
    private BigDecimal latitude;
    private BigDecimal longitude;
    private String supportStructureTypePresent;
    private String poleTypePresent;
    private String conductorTypePresent;
    private String conductorSizePresent;
    private String createdByUsername;
    private String poleAbSwitchPresent;
//    private String usagetype;
//    private String htFeederCode;
//    private String htFeederName;
//    private String ssCodeBck;
    private Integer schemeType;
    private String numberOfCircuitPresent;
    private String regionCode;
    private String regionName;
//    private Boolean isMobileServey;
//    private Integer poleLocationType;
//    private Integer endPoint;
//    private Integer tapPoint;
//    private String parentPoleCodeBackup;
    private String wkbGeometryJson;
    private String subStationCodeBak;
//    private String crossingType;
    private LocalDateTime actiontimestamp;
//    private String groupid;

//    extra variable to find DTR Pole
    private String isDtrPole;
}
